Add codes to admin levels.
geocoder-php/Geocoder pull request #1112
Opened 2021-01-22 09:56 UTC by gbs

Hi Jonathan,

We're moving towards using Pelias for geocoding, using the provider you wrote. We would like to use the codes for administrative regions as well, hence my pull request.

Examples to support the change:

### Location before adding the admin level code

```php
object(Camptoo\Geocoding\GeocoderLocation) {
	[protected] location => object(Geocoder\Model\Address) {
		[private] coordinates => object(Geocoder\Model\Coordinates) {
			[private] latitude => (float) 51.946443
			[private] longitude => (float) 4.509113
		}
		[private] bounds => object(Geocoder\Model\Bounds) {
			[private] south => (float) 52.332531
			[private] west => (float) 5.149456
			[private] north => (float) 51.64378
			[private] east => (float) 3.786154
		}
		[private] streetNumber => null
		[private] streetName => null
		[private] subLocality => null
		[private] locality => null
		[private] postalCode => null
		[private] adminLevels => object(Geocoder\Model\AdminLevelCollection) {
			[private] adminLevels => [
				(int) 1 => object(Geocoder\Model\AdminLevel) {
					[private] level => (int) 1
					[private] name => 'Zuid-Holland'
					[private] code => null
				},
				(int) 5 => object(Geocoder\Model\AdminLevel) {
					[private] level => (int) 5
					[private] name => 'Netherlands'
					[private] code => null
				}
			]
		}
		[private] country => object(Geocoder\Model\Country) {
			[private] name => 'Netherlands'
			[private] code => 'NLD'
		}
		[private] timezone => null
		[private] providedBy => 'pelias'
	}
}
```

### Result from Pelias

![image](https://user-images.githubusercontent.com/1067163/104210963-c891dd80-5433-11eb-9377-202f2fd2a7be.png)

### Location after adding the admin level code

```php
object(Camptoo\Geocoding\GeocoderLocation) {
	[protected] location => object(Geocoder\Model\Address) {
		[private] coordinates => object(Geocoder\Model\Coordinates) {
			[private] latitude => (float) 51.946443
			[private] longitude => (float) 4.509113
		}
		[private] bounds => object(Geocoder\Model\Bounds) {
			[private] south => (float) 52.332531
			[private] west => (float) 5.149456
			[private] north => (float) 51.64378
			[private] east => (float) 3.786154
		}
		[private] streetNumber => null
		[private] streetName => null
		[private] subLocality => null
		[private] locality => null
		[private] postalCode => null
		[private] adminLevels => object(Geocoder\Model\AdminLevelCollection) {
			[private] adminLevels => [
				(int) 1 => object(Geocoder\Model\AdminLevel) {
					[private] level => (int) 1
					[private] name => 'Zuid-Holland'
					[private] code => 'ZH'
				},
				(int) 5 => object(Geocoder\Model\AdminLevel) {
					[private] level => (int) 5
					[private] name => 'Netherlands'
					[private] code => 'NLD'
				}
			]
		}
		[private] country => object(Geocoder\Model\Country) {
			[private] name => 'Netherlands'
			[private] code => 'NLD'
		}
		[private] timezone => null
		[private] providedBy => 'pelias'
	}
}
```

Hope you like the addition.

Best regards

2021-03-30 08:58 UTC, jbelien commented
Thanks @gbs !

I'll review it ASAP. Could you already make sure the formatting is correct (see <https://github.styleci.io/analyses/Yj5KnG>) ?

2021-03-30 10:02 UTC, gbs commented
Hi @jbelien,

The formatting is correct now. The build is failing, but I see this is on the master branch as well.

Since we're starting to use Pelias in more features, support for localization and layers was added. Also I improved the tests a bit by checking the query data from the request.

2022-07-30 10:06 UTC, jbelien requested changes

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +        $data = array_filter([
Why `array_filter` without any callback function ?

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +            'lang' => $query->getLocale() ?? 'en',
Is `lang` paramater required by Pelias ?

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +    public const VALID_LAYERS = [
Could you add a comment with a link to the documentation about those layers ?

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +                ::createFromArray([
```suggestion
            $results[] = PeliasAddress::createFromArray([
```

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +        }
```suggestion
        if (!is_array($layers)) {
            throw new LogicException('Layers must be an array');
        }
        if (count($layers) === 0) {
            return null;
        }
```

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Pelias.php
> +        if (!empty($invalidLayers)) {
```suggestion
        if (count($invalidLayers) > 0) {
```

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/Tests/PeliasTest.php
> +use function urlencode;
```suggestion
```

Not necessary.

2022-07-30 10:06 UTC, jbelien commented on src/Provider/Pelias/composer.json
> +        "ext-json": "^7.3 || ^8.0",
I don't think this is necessary!

2023-06-30 01:18 UTC, closed without merging