Filters GoogleMap results with components
geocoder-php/Geocoder pull request #1154
Opened 2022-05-13 13:58 UTC by spike31

Explain how to filters GoogleMap results with components

2022-05-27 09:01 UTC, jbelien requested changes
Thanks a lot @spike31 ; really good idea to extend the documentation. 👍

2022-05-27 09:01 UTC, jbelien commented on src/Provider/GoogleMapsPlaces/README.md
> +matches a country name or a two letter ISO 3166-1 country code. If you only use the "region" parameter, you will not be guaranteed to have results on the region, as the documentation indicates [Regio
The beginning of that paragraph seems to be a part missing...

2022-05-27 09:01 UTC, jbelien commented on src/Provider/GoogleMapsPlaces/README.md
> +    GeocodeQuery::create('montpe')
```suggestion
    GeocodeQuery::create('montpellier')
```
It will be more clear with the full name of the city.

2022-05-30 11:23 UTC, spike31 commented
Hi @jbelien,

I have updated my PR

2022-06-07 15:00 UTC, jbelien approved these changes

2022-06-07 15:04 UTC, merged